### ISSUE TITLE
Bitfield render

### ISSUE THREAD

**Issue by RuvenSalamon** [cisco-sas/kitty#67]
Hi,

Bitfields seem to affect the rendering of fields that follow.

**Reproduce**

```
from kitty import model

_fields = [
    model.UInt16(1),
    model.BitField(0, 1),
    model.UInt16(1m)
]

temp = model.Template(fields=_fields)

print(temp.render())
```
**Expected Result**
`0x000100001`  

**Result**
`0x0001000080`

**Comment by BinyaminSharet** [comment]
Hi @RuvenSalamon 

Thanks for reporting. However, this is not a bug, and this behaviour is not related to `BitField`.
A template is always byte-aligned, by design, and if the number of bits in the template is not a multiple of 8, it will be padded with 0 bits.

In the case you provide, there are 33 bits from the fields: 16 (UInt16) + 1 (BitField with length 1) + 16 (UInt16), and they are padded by 7 bits, which leads to binary `00000000 00000001 00000000 00000000 10000000` which is `0001000080` in hex.
