### ISSUE TITLE
Boo or Kitty?

### ISSUE THREAD

**Issue by GH0st3rs** [cisco-sas/kitty#73]
> *Sulley: Boo?*
> *Boo: Kitty!*

```python
>>> from kitty.model import String
>>> String('hello').num_mutations()
91
```

```python
>>> from boofuzz import *
>>> s_initialize("user")
>>> s_string('hello')
>>> s_get('user').num_mutations()
1441
```

**Comment by BinyaminSharet** [comment]
This is not really an issue, so I'm going to close it :) and I'm not very into convincing people this way or the other. BUT - over time we refined the list of strings and string mutations that String() generates. We found out that many are domain-specific, or just redundant because many just trigger buffer overflows and you don't need that many options in most cases and they add many tests that are not really necessary. However, you can always add a strings file that string will load and use them if you have a kitty_strings.txt file in the current directory see [here](https://github.com/cisco-sas/kitty/blob/f19e81124c08d926fdba533ed58ddbc4a941bdf5/kitty/model/low_level/field.py#L615)
